### ISSUE TITLE
Implement the "That's Not Food" button

### ISSUE THREAD

**Issue by jeffDevelops** [oakesrandall/project3#87]
I can't open your project by cloning your repo, because you've `.gitignore`d your API key, so I wanted to explore something I remembered from your presentation. The images that you get from your Google Places API are not always of food. What if, at the very least, it dismissed the photo, like your "swipe left" functionality? 

A super stretch goal with this (i.e., definitely not necessary to close the issue) could be to cache the image URL and store it in your database as something like a "don't show this image" list, and if your program comes across the same URL when making future API calls, if it appears in your cache, you move onto the next restaurant.

**Comment by oakesrandall** [comment]
Not food button has functionality.
